### ISSUE TITLE
process_plink() overwrite

### ISSUE THREAD

**Issue by oscarrys** [pbreheny/plmmr#26]
I noticed that if you attempt to rerun process_plink(), you get the message `Error: File 'prefix.bk' already exists.` I had to look around in the file system and manually remove the processed files before proceeding. I'm wondering if there could be an 'overwrite' option in this function to create new .bk and .rds files in case, say, one wanted to change the imputation method that is used?

**Comment by pbreheny** [comment]
I think this is a good idea.

**Comment by tabpeter** [comment]
This will be a feature in the soon-to-be-released version 3.0 of `plmmr`; see [944132b](https://github.com/pbreheny/plmmr/commit/944132b20619cee9c944c27e165a863f1f60bd44)
